###**Note: To work on colab we have to mount google drive**

In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


# **1. NumPy**
- NumPy(Numerical Python) is the fundamental package for scientific computing in Python

```
import numpy as np
```

### **1.1 Import Library**

In [1]:
import numpy as np

### **1.2 Array Creation**
- The general mechanisms for creating arrays:
- (i). Conversion from other Python structures (i.e. lists and tuples)
- (ii). Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
- (iii). Replicating, joining, or mutating existing arrays
- (iv). Reading arrays from disk, either from standard or custom formats.

### **Example 1:**

In [2]:
#Creating an array using list
arr1D=np.array([1,2,3,4])
print(arr1D)

#Creating an array using dictionary
arrdict= {"key1":1,
          "key2":2,
          "key3":3,
          "key4":4
          }
np_array=np.array(list(arrdict.values()))
print(np_array)



[1 2 3 4]
[1 2 3 4]


### **Example 2:**
- Multidimensional array

In [3]:
arr2D=np.array([[1,2,3],[3,7,9]])
print(arr2D)
print("Dimensions: ",arr2D.ndim)
print("Shape: ",arr2D.shape)
print("Data Type",arr2D.dtype)

[[1 2 3]
 [3 7 9]]
Dimensions:  2
Shape:  (2, 3)
Data Type int64


### **Example 3:**
- Manipulating data type
- An n-bit signed integer represents integers from -2^n-1 to 2^n-1
- If you are not careful with dtype assignments, you can get unwanted overflow, as such

In [5]:
arrtype=np.array([127,128,129],dtype=np.int8)
print(arrtype)

[ 127 -128 -127]


/tmp/ipykernel_7801/1278412645.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arrtype=np.array([127,128,129],dtype=np.int8)
/tmp/ipykernel_7801/1278412645.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arrtype=np.array([127,128,129],dtype=np.int8)


### **Example 4:
- The ndarray creation functions e.g. numpy.ones, numpy.zeros, and random define arrays based upon the desired shape

In [6]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [8]:
np.eye(2, 2)

array([[1., 0.],
       [0., 1.]])

- Other functions include



In [ ]:
d = np.arange(10,25,5)#Create an array of evenly spaced values (step value)
np.linspace(0,2,9)#Create an array of evenly spaced values (number of samples)
e = np.full((2,2),7)#Create a constant array
f = np.eye(2)#Create a 2X2 identity matrix
np.random.random((2,2))#Create an array with random values
np.empty((3,2))#Create an empty array

### **1.3 Input/Ouput Operations**
#### **Example 1:**
- Save numpy array to a txt file

In [17]:
data = np.array([250,10,13,44])
np.savetxt('/content/drive/MyDrive/Colab Notebooks/output.txt',data,delimiter=',',fmt="%d")

In [19]:
#load txt file
np.loadtxt('/content/drive/MyDrive/Colab Notebooks/output.txt')


array([250,  10,  13,  44])

## **How do we manipulate CSV file using numpy?**
###**Home Task**


### **1.4 Arithmetic Operations**
### **Example:**



In [22]:
#Addition
arrA=np.array([25,33,45])
arrB=np.array([2,3,14,21])
add=arrA+3
print(add)

[28 36 48]


In [23]:
#Subraction
sub=arrA-arrB
print(sub)

[24 24 39]


In [26]:
#multiplication
multiply=arrA*2
print(multiply)
#using function
func_multi=np.multiply(arrA,arrB)
print(func_multi)

[50 66 90]
[ 25 297 270]


### **1.5. Array Manipulation**
###  **1.5.1. Broadcasting**
- The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
### **Example:**

In [34]:
#builtin Broadcasting
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b=x+y
print("Built-In broadcasting",b)
#Manual Broadcasting
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
print("manual broadcasting",out)

Built-In broadcasting [[5 6 7]
 [6 7 8]
 [7 8 9]]
manual broadcasting [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


###  **1.5.2. Transpose**
- The transpose of an array swaps its rows and columns
### **Example:**

In [41]:
arrT = np.array([[1, 2, 3],
                [4, 5, 6]])
transpose = np.transpose(arrT) #OR use transpose = arr.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


###  **1.5.3. Changing Shape**
### **Example 1:**
-The reshape() method allows you to change the shape of an array without changing its data

In [54]:
arr_r = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with 2 rows and 3 columns
reshaped_arr = arr_r.reshape(2, 3)

print("Original Array (1D):")
print(arr_r)

print("\nReshaped Array (2D):")
print(reshaped_arr)

Original Array (1D):
[1 2 3 4 5 6]

Reshaped Array (2D):
[[1 2 3]
 [4 5 6]]


In [55]:
arr_reshape=arrT.reshape(-1)
print(arr_reshape)

[1 2 3 4 5 6]


###  **1.5.4. Adding/Removing elements**
### **Example:**
**Note:**    
- axis=0: Indicates operation along the rows (vertically).
- axis=1: Indicates operation along the columns (horizontally).
- axis=None: Indicates operation on the flattened array, considering all elements.

In [63]:
#Deleting element
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d_deleted_row = np.delete(arr_2d, 0, axis=0) #np.delete(array,index,axis=row/column)
print("\nDeleting",arr_2d_deleted_row)

#To add items insert,append,concatenate and hstack etc functions are used
new_arr_2d = np.insert(arr_2d_deleted_row, 1, [10, 11, 12], axis=0)
print("\nAdding:",new_arr_2d)


Deleting [[4 5 6]
 [7 8 9]]

Adding: [[ 4  5  6]
 [10 11 12]
 [ 7  8  9]]


###  **1.5.5 Subsetting,Indexing and Slicing**
### **Example- Subsetting**

In [64]:
arr_2d[2] #Select the element at the 2nd index

array([7, 8, 9])

In [66]:
arr_2d[2,2] #Select the element at row 1 column 2 (equivalent to b[1][2])

9

### **Example - Boolean Indexing**


In [68]:
arr_2d[arr_2d<3] #Select elements from a less than 2

array([1, 2])

### **Example - Fancy Indexing**
- Fancy indexing in NumPy refers to the practice of indexing an array using an array of indices or boolean masks.

**Using Arrays of Indices:**

In [69]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
result = arr[indices]

print("REsult: ",result)


REsult:  [1 3 5]


**Using Boolean Masks:**


In [70]:
mask=arr[arr>3]
print(mask)

[4 5]
